/*
npx sequelize-cli migration:generate --name master_product
npx sequelize-cli migration:generate --name product_inventory
npx sequelize-cli migration:generate --name inventory_history
npx sequelize-cli migration:generate --name product_price
npx sequelize-cli migration:generate --name price_history
npx sequelize-cli migration:generate --name master_branch
*/
const Inventory ={
    master_product: {
      tablename: "master_product",
      prefix: "mp_",
      insertColumns: [
        "vendor_id",
        "upc",
        "code",
        "description",
        "category",
        "subcategory",
        "status",
      ],
      selectColumns: [
        "mp_id",
        "mp_vendor_id",
        "mp_upc",
        "mp_code",
        "mp_description",
        "mp_category",
        "mp_subcategory",
        "mp_status",
      ],
      selectOptionsColumn: {
        id: "mp_id",
        vendor_id: "mp_vendor_id",
        upc: "mp_upc",
        code: "mp_code",
        description: "mp_description",
        category: "mp_category",
        subcategory: "mp_subcategory",
        status: "mp_status",
      },
    },
    product_inventory: {
      tablename: "product_inventory",
      prefix: "pi_",
      insertColumns: [
        "product_id",
        "branch_id",
        "quantity",
        "unit",
        "status",
      ],
      selectColumns: [
        "pi_id",
        "pi_product_id",
        "pi_branch_id",
        "pi_quantity",
        "pi_unit",
        "pi_status",
      ],
      selectOptionsColumn: {
        id: "pi_id",
        product_id: "pi_product_id",
        branch_id: "pi_branch_id",
        quantity: "pi_quantity",
        unit: "pi_unit",
        status: "pi_status",
      },
    },
    inventory_history: {
        tablename: "inventory_history",
        prefix: "ih_",
        insertColumns: [
            "inventory_id",
            "date",
            "transaction_type",
            "quantity",
            "unit",
        ],
        selectColumns: [
            "ih_id",
            "ih_inventory_id",
            "ih_date",
            "ih_transaction_type",
            "ih_quantity",
            "ih_unit",
        ],
        selectOptionsColumn: {
            id: "ih_id",
            inventory_id: "ih_inventory_id",
            date: "ih_date",
            transaction_type: "ih_transaction_type",
            quantity: "ih_quantity",
            unit: "ih_unit",
        },
    },
    product_price: {
        tablename: "product_price",
        prefix: "pp_",
        insertColumns: [
            "product_id",
            "cost",
            "markup_rate",
            "vat_ex",
            "vat_inc",
            "status",
        ],
        selectColumns: [
            "pp_id",
            "pp_product_id",
            "pp_cost",
            "pp_markup_rate",
            "pp_vat_ex",
            "pp_vat_inc",
            "pp_status",
        ],
        selectOptionsColumn: {
            id: "pp_id",
            product_id: "pp_product_id",
            cost: "pp_cost",
            markup_rate: "pp_markup_rate",
            vat_ex: "pp_vat_ex",
            vat_inc: "pp_vat_inc",
            status: "pp_status",
        },
    },
    price_history: {
        tablename: "price_history",
        prefix: "ph_",
        insertColumns: [
            "product_id",
            "cost",
            "markup_rate",
            "vat_ex",
            "vat_inc",
            "date",
        ],
        selectColumns: [
            "ph_id",
            "ph_product_id",
            "ph_cost",
            "ph_markup_rate",
            "ph_vat_ex",
            "ph_vat_inc",
            "ph_date",
        ],
        selectOptionsColumn: {
            id: "ph_id",
            product_id: "ph_product_id",
            cost: "ph_cost",
            markup_rate: "ph_markup_rate",
            vat_ex: "ph_vat_ex",
            vat_inc: "ph_vat_inc",
            date: "ph_date",
        },
    },
    master_branch: {
        tablename: "master_branch",
        prefix: "mb_",
        insertColumns: [
          "code",
          "description",
          "email",
          "phone",
          "mobile",
          "address",
          "manager",
          "status",
        ],
        selectColumns: [
          "mb_id",
          "mb_code",
          "mb_description",
          "mb_email",
          "mb_phone",
          "mb_mobile",
          "mb_address",
          "mb_manager",
          "mb_status",
        ],
        selectOptionsColumn: {
          id: "mb_id",
          code: "mb_code",
          description: "mb_description",
          email: "mb_email",
          phone: "mb_phone",
          mobile: "mb_mobile",
          address: "mb_address",
          manager: "mb_manager",
          status: "mb_status",
        },
      },
}
    
exports.Inventory = Inventory;
